// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwk0Z58SWdSVeMpzzj3bPBmGZAPGVXBWA',
    appId: '1:843971353457:web:e17de6c6ea0537ec7134d0',
    messagingSenderId: '843971353457',
    projectId: 'my-flutter-shop-lynel',
    authDomain: 'my-flutter-shop-lynel.firebaseapp.com',
    storageBucket: 'my-flutter-shop-lynel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB98gezRZWDLz1CdTv64uBTK7rVJZyjekA',
    appId: '1:843971353457:android:f9f8d06be31deb077134d0',
    messagingSenderId: '843971353457',
    projectId: 'my-flutter-shop-lynel',
    storageBucket: 'my-flutter-shop-lynel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLg89Lryx9QYI0irG5415PFQqK7mH-fio',
    appId: '1:843971353457:ios:0a2e610b519a90297134d0',
    messagingSenderId: '843971353457',
    projectId: 'my-flutter-shop-lynel',
    storageBucket: 'my-flutter-shop-lynel.firebasestorage.app',
    iosBundleId: 'com.example.lynelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLg89Lryx9QYI0irG5415PFQqK7mH-fio',
    appId: '1:843971353457:ios:0a2e610b519a90297134d0',
    messagingSenderId: '843971353457',
    projectId: 'my-flutter-shop-lynel',
    storageBucket: 'my-flutter-shop-lynel.firebasestorage.app',
    iosBundleId: 'com.example.lynelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwk0Z58SWdSVeMpzzj3bPBmGZAPGVXBWA',
    appId: '1:843971353457:web:d9f74231f9e702937134d0',
    messagingSenderId: '843971353457',
    projectId: 'my-flutter-shop-lynel',
    authDomain: 'my-flutter-shop-lynel.firebaseapp.com',
    storageBucket: 'my-flutter-shop-lynel.firebasestorage.app',
  );
}
